name: 'Install a Visual Studio Extension' 
description: 'Download the latest extension version and install in Visual Studio'
inputs:
  packagename: 
    description:  'Package names from the Visual Studio Marketplace URL itemName parameter'
    required: true
runs:
  using: "composite"
  steps:
    - id: vsix
      shell: pwsh
      run: .\vsix-install-package.ps1 ${{ inputs.packagename }}