name: Test install-vsix action

on:
  push:
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
jobs: 
  test-install-vsix:
    name: Test local install-vsix Package
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2
       
    - name: Show Visual Studio locator information
      run: vswhere.exe

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - uses: ./
      name: Test installing nanoFramework extension
      with: 
        packagename: 'nanoframework.nanoFramework-VS2019-Extension'